### ISSUE TITLE
Documentation of structural design

### ISSUE THREAD

**Issue by EvaWie** [openego/oemof.powerflow#2]

**Comment by cswh** [comment]
I had to postpone the milestone until Friday.

**Comment by chrisflei** [comment]
And update yet on the documentation?

**Comment by cswh** [comment]
Sorry for the delay. Keep working in the dev branch. If anything is not clear create an issue and assign it to me. Good luck ;)

**Comment by chrisflei** [comment]
Thanks @cswh 
Getting started on the code now
