### ISSUE TITLE
Create first working version

### ISSUE THREAD

**Issue by EvaWie** [openego/oemof.powerflow#3]
- class structure including attributes and methods
- mininmal example

**Comment by ulfmueller** [comment]
@cswh and @chris-fleischer: What do you think, should we present/discuss (and further develop) the first working version at the oemof dev days (9th-11th of may). @gplssm would come then as well and would be interested in such a setting.

**Comment by chrisflei** [comment]
Im sure on the workload yet so not sure whether a working minimal example will be ready by then

**Comment by gplssm** [comment]
Is there an updated schedule regarding the first working version?

**Comment by cswh** [comment]
I changed the due date for the milestone.

The plan now is to use PyPSA directly for the first simulations. In January we will see if we go for a deeper integration of PyPSA and oemof.

**Comment by simnh** [comment]
The plan is now to integrate pyPSA in oemof (new API v0.1.1) so we will discuss this mainly in
oemof issue/pull request and maybe in the eGo.powerflow repository. Once the issue exists, I will cross reference it here...

**Comment by gplssm** [comment]
Interesting news! I'm curious about the implementation plan!

Keep us updated and ask for help/participation in webko's to define things there

**Comment by simnh** [comment]
This will be the corresponding oemof issue: 

https://github.com/oemof/oemof/issues/246
See pull request: 
https://github.com/oemof/oemof/pull/250

**Comment by simnh** [comment]
We will integrate pypsa inside the  oemof repository as an own library (module or package). This is why we maybe do not need this repo here anymore  (see #6 ). 

For now I would create a feature branch in the ego.powerflow repository to test the new oemof.powerflow functionality inside ego, meaning as an oemof application. If that’s ok with you? 
This won't interfere with any other code there because it will be an complete new file. I would then create a pull request at some point in time...

**Comment by ulfmueller** [comment]
Since we talked about this in real, I think this is a good workflow. Whether we are able to switch to the newly created pypsa-oemof-integration we have to figure once you successfully created/tested the integration...

**Comment by gplssm** [comment]
Good approach! I think the _open_eGo_ consortium should discussion structure of ego.powerflow in the near future. Considering you totally-new-file-approach this does not have to bother you now, @simnh.

**Comment by cswh** [comment]
obsolete
