### ISSUE TITLE
Assigning attributes 

### ISSUE THREAD

**Issue by chrisflei** [openego/oemof.powerflow#4]
There is the minimal_example.py which adds each component separately and which I thought could be used as a first target to be integrated in oemof. 
I've constructed the sub classes and certain minimal attributes as per minimal_example.py in oemof_powerflow.py. 
In the powerflow_example.py I've started creating two buses (bus_1 and bus_2) with their attributes. When I try to add bus_1 using the network.add function of PyPSA I receive the error that the attribute 'name' has not been assigned although I have the attribute in bus_1.
Is this a possible way of integrating PyPSA in oemof ? How do I get past the attribution error?
@cswh

**Comment by chrisflei** [comment]
Attribution error solved. Now working on Energy system class

**Comment by cswh** [comment]
Good, that you could solve it. Next time feel free to assign the issue to me, then the chances are higher to get a more rapid response ;)
