### ISSUE TITLE
Deleting this repository at some point

### ISSUE THREAD

**Issue by simnh** [openego/oemof.powerflow#6]
The idea of the process is now: 

- create the powerflow oemof-pypsa integration in the oemof repository (see https://github.com/oemof/oemof/pull/250) 
- use this functionality to perform lopf, pf inside ego.powerflow repository as an oemof application 

If that's ok with every one we would not need this repository anymore. As here has not been discussed and pushed much we can delete or at least archive it. 
What do you think?

**Comment by gplssm** [comment]
Good initiative!
I'm glad, that you give a try to bring open_ego, oemof and PyPSA together!
You got my _GO_ to delete this repo.
